# -*- coding: utf-8 -*-
"""crop-recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12TIWSp-kK3UBP3QJDDTM6R6LIIo0TWYR

## Import All Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time

from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.model_selection import train_test_split, GridSearchCV,RandomizedSearchCV
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder,OneHotEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

"""## Load Data"""

df = pd.read_csv('/content/Crop_recommendation.csv')
df

"""## Data Analysis : EDA"""

df.columns

df['label'].unique()

df.info()

df.duplicated()

plt.figure(figsize=(10,10))
df['label'].value_counts().plot(kind='pie',autopct="%.1f%%")
plt.show()

df['label'].value_counts()

"""## Skewness in data"""

df.iloc[:,:-1].skew()

"""## Target Column"""

class_labels = df['label'].unique().tolist()
class_labels

le = LabelEncoder()
df['label'] = le.fit_transform(df['label'])

df['label']

class_labels = le.classes_
class_labels

df

"""## Split The Data"""

x = df.drop('label',axis=1)
y = df['label']
x

# Correlation matrix
plt.figure(figsize = (10,10))
correlation_matrix = x.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='RdYlGn')

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,shuffle=True)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import time
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Assuming X_train, Y_train, X_test, Y_test are already defined

# Define classifiers
classifiers = {
    "RandomForest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "XGBoost": XGBClassifier(eval_metric='mlogloss'),
    "GradientBoosting": GradientBoostingClassifier(),
    "NaiveBayes": GaussianNB(),
    "SVM": SVC(),
    "Decision Tree": DecisionTreeClassifier(),
    "Logistic Regression": LogisticRegression(max_iter=10000)
}

# Prepare table to store results
results = []
_pred = clf.predict(x_test)
    end_test = time.time()

    # Compute metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted', zero_division=1)
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    training_time = end_train - start_train
    testing_time = end_test - start_test
# Loop through classifiers and compute metrics
for name, clf in classifiers.items():
    # Record the start time for training
    start_train = time.time()
    clf.fit(x_train,y_train)
    end_train = time.time()

    # Record the start time for testing
    start_test = time.time()
    y

    # Compute confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred)

    # Append the results to the list
    results.append({
        "Classifier": name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "Training Time": training_time,
        "Testing Time": testing_time,
        "Confusion Matrix": conf_matrix
    })

    # Plot confusion matrix
    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
    plt.title(f"Confusion Matrix for {name}")
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.show()

# Convert results to a DataFrame for better visualization
results_df = pd.DataFrame(results)

results_df

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import label_binarize
from itertools import cycle
from xgboost import XGBClassifier  # Ensure you have XGBoost imported

# Binarize the labels if it's a multi-class classification problem
y_train_binarized = label_binarize(y_train, classes=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])
y_test_binarized = label_binarize(y_test, classes=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])
n_classes = y_test_binarized.shape[1]

# Initialize the XGBoost classifier
xgb_clf = XGBClassifier(eval_metric='mlogloss')

# Fit the classifier and get the predicted probabilities
xgb_clf.fit(x_train, y_train_binarized)
y_score = xgb_clf.predict_proba(x_test)

# Compute ROC curve and AUC for each class
fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc[i] = roc_auc_score(y_test_binarized[:, i], y_score[:, i])

# Compute micro-average ROC curve and AUC
fpr["micro"], tpr["micro"], _ = roc_curve(y_test_binarized.ravel(), y_score.ravel())
roc_auc["micro"] = roc_auc_score(y_test_binarized, y_score, average="micro")

# Plotting the ROC curve for each class
plt.figure(figsize=(10, 8))
colors = cycle(['aqua', 'darkorange', 'cornflowerblue', 'green', 'red', 'purple', 'yellow', 'cyan', 'pink', 'brown', 'blue', 'magenta', 'gold', 'lime', 'black'])

for i, color in zip(range(n_classes), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=2, label=f'Class {i} (AUC = {roc_auc[i]:0.2f})')

# Plot micro-average ROC curve
plt.plot(fpr["micro"], tpr["micro"], color='deeppink', linestyle=':', linewidth=4, label=f'Micro-average (AUC = {roc_auc["micro"]:0.2f})')

# Plot settings
plt.plot([0, 1], [0, 1], 'k--', lw=2)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('AUC-ROC Curve for XGBoost (Multi-class)')
plt.legend(loc="lower right")
plt.grid()
plt.show()

## new inputs


N = 40
P = 50
k = 50
temperature = 40.0
humidity = 20
ph = 100
rainfall = 100

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")t")



